version: "3.8"

services:
  db:
    image: postgres:16.3
    container_name: SWIFT-API-DB
    environment:
      POSTGRES_DB: swift
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: remitly2025
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "swift"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s

  backend:
    build: .
    container_name: SWIFT-API
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADDR: ":8080"
      EXTERNAL_URL: "http://localhost:8080"
      DB_ADDR: "postgres://admin:remitly2025@db/swift?sslmode=disable"
      DB_MAX_OPEN_CONNS: 30
      DB_MAX_IDLE_CONNS: 30
      DB_MAX_IDLE_TIME: "15m"
      ENV: "production"
      API_VERSION: "v1"
      GOOSE_MIGRATION_DIR: "./cmd/migrations"
    ports:
      - "8080:8080"

volumes:
  db-data:
