services:
  db:
    image: postgres:16.3
    container_name: SWIFT-API-POSTGRES
    environment:
      POSTGRES_DB: swift
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: remitly2025
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: SWIFT-API
    depends_on:
      - db
    environment:
      ADDR: ":8080"
      EXTERNAL_URL: "http://localhost:8080"
      DB_ADDR: "postgres://admin:remitly2025@db:5432/swift?sslmode=disable"
      DB_MAX_OPEN_CONNS: 30
      DB_MAX_IDLE_CONNS: 30
      DB_MAX_IDLE_TIME: "15m"
      ENV: "production"
      API_VERSION: "v1"
      GOOSE_MIGRATION_DIR: "./cmd/migrations"
    ports:
      - "8080:8080"

volumes:
  db-data:
