services:
  db:
    image: postgres:16.3
    container_name: SWIFT-API-DB
    environment:
      POSTGRES_DB: swift
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: remitly2025
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - "5432:5432"

volumes:
  db-data: